name: Pull Request CI

on:
  pull_request:
    branches:
      - 'master'
      - 'release*'
# Um workflow é composto de um ou mais Jobs que podem ser executados sequencialmente ou em paralelo
jobs:
  # Este Workflow contém dois Jobs chamados "test" e "build-and-deploy"
  test:
    name: Run Unit Tests
    # O tipo de runner em que o job será executado
    runs-on: ubuntu-latest  
    # Steps representam a sequencia de tarefas usando o shell runners que serão executadas como parte do Job
    steps:
    - uses: actions/checkout@v1
    #  Step para instalar o NDK
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    #  Step para rodar testes unitários
    - name: Unit tests
      run: ./gradlew test --stacktrace
  
  build-and-generate-apk:
    # O tipo de runner em que o job será executado
    runs-on: ubuntu-latest
    # Steps representam a sequencia de tarefas usando o shell runners que serão executadas como parte do Job
    steps:
    - uses: actions/checkout@v1
    # Step para Configurar o JDK
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8       
    - name: build release
      run: ./gradlew assembleRelease
    # Step para salvar a APK como Artifact
      continue-on-error: false
    - name: upload artefact to App Center
      uses: wzieba/AppCenter-Github-Action@v1.2.1
      with:
        appName: baiana/github-api-test
        token: ${{secrets.APP_CENTER_TOKEN}}
        group: Collaborators
        file: app/build/outputs/apk/release/app-release.apk
      continue-on-error: false
      
    
